language: generic 

sudo: required
services :
  - docker

before_install:
  - docker build -t nithinpulivarthi/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nithinpulivarthi/docker-react npm run test -- --coverage
   