language: generic 

sudo: required
services :
  - docker

before_install:
  - docker build -t nithinpulivarthi/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nithinpulivarthi/docker-react npm run test

deploy:
  provider: elasticbeanstack
  region: "us-east-2"
  app: docker-react
  env: DockerReact-env
  bucket_name: elasticbeanstalk-us-east-2-167741058917
  bucket_path: docker-react
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY

   